export type PlaceCategory =
  | "coffee"
  | "food"
  | "bar"
  | "winery"
  | "sightseeing"
  | "stay"
  | "parkrun";

export type Place = {
  slug: string;
  name: string;
  category: PlaceCategory;
  city: string;
  note: string;
  mapsUrl: string;
  images?: string[];
};

export const mapEmbedUrl =
  "https://www.google.com/maps/d/embed?mid=1F_I0lplYNoAdVhfaczM97I_Gm9_ZYXU";

export const mapsListUrl =
  "https://www.google.com/maps/d/viewer?mid=1F_I0lplYNoAdVhfaczM97I_Gm9_ZYXU";

export const places: Place[] = [
  // ── Sydney ──────────────────────────────────────────────────────────────
  {
    slug: "the-baxter-inn",
    name: "The Baxter Inn",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8696238,151.2055976",
  },
  {
    slug: "maybe-sammy",
    name: "Maybe Sammy",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8617706,151.2069595",
  },
  {
    slug: "the-barber-shop",
    name: "The Barber Shop",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.869557,151.2059828",
  },
  {
    slug: "old-mates-place",
    name: "Old Mate's Place",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8695467,151.205153",
  },
  {
    slug: "opera-bar",
    name: "Opera Bar",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8584964,151.2136249",
  },
  {
    slug: "deadwax",
    name: "Deadwax",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.899319,151.1723418",
  },
  {
    slug: "the-caterpillar-club",
    name: "The Caterpillar Club",
    category: "bar",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8672489,151.2086816",
  },
  {
    slug: "evies-redfern",
    name: "Evie's Redfern",
    category: "coffee",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.892701,151.2144219",
  },
  {
    slug: "social-society",
    name: "Social Society",
    category: "coffee",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.9055307,151.2036867",
  },
  {
    slug: "quick-brown-fox-eatery",
    name: "Quick Brown Fox Eatery",
    category: "coffee",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8694146,151.1947574",
  },
  {
    slug: "rovollo-restaurant",
    name: "Rovollo Restaurant and Wine Room",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8683054,151.2093149",
  },
  {
    slug: "morena",
    name: "Morena",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8675318,151.2073445",
  },
  {
    slug: "cin-yen",
    name: "Cin Yen Indonesian Medan Food",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8913954,151.1957541",
  },
  {
    slug: "sushi-mori",
    name: "Sushi-mori",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8864078,151.2078443",
  },
  {
    slug: "bopp-and-tone",
    name: "Bopp & Tone",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8668185,151.2064637",
  },
  {
    slug: "maeda-newtown",
    name: "Maeda Newtown",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.9038085,151.179753",
  },
  {
    slug: "the-gidley",
    name: "The Gidley",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8692214,151.2101555",
  },
  {
    slug: "rainieris-deli",
    name: "Raineri's Continental Delicatessen",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8693667,151.129304",
  },
  {
    slug: "pellegrino-2000",
    name: "Pellegrino 2000",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8800003,151.2098913",
  },
  {
    slug: "palace-chinese-restaurant",
    name: "Palace Chinese Restaurant",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8719036,151.2090017",
  },
  {
    slug: "vinh-phat",
    name: "Vinh Phat Chinese Seafood Restaurant",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8937035,150.9374564",
  },
  {
    slug: "bistro-grenier",
    name: "Bistro Grenier",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8959953,151.1810454",
  },
  {
    slug: "louie",
    name: "Louie",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.9232022,151.2560188",
  },
  {
    slug: "mensho-tokyo-ramen-sydney",
    name: "Mensho Tokyo Ramen Sydney",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8696428,151.2065571",
  },
  {
    slug: "four-ate-five",
    name: "Four Ate Five",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8881135,151.2132272",
  },
  {
    slug: "takam",
    name: "Takam, Filipino Food Forward",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.877065,151.2219388",
  },
  {
    slug: "bar-luca",
    name: "Bar Luca",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.863968,151.211934",
  },
  {
    slug: "black-star-pastry",
    name: "Black Star Pastry Sydney CBD",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8724566,151.2078496",
  },
  {
    slug: "bourke-street-bakery",
    name: "Bourke Street Bakery Surry Hills",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8894017,151.2148985",
  },
  {
    slug: "o-bar-and-dining",
    name: "O Bar and Dining",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8649023,151.207767",
  },
  {
    slug: "cafe-paci",
    name: "Cafe Paci",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.8932057,151.1837679",
  },
  {
    slug: "lokha",
    name: "LOKHA",
    category: "food",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.9109332,151.2019103",
  },
  {
    slug: "circular-quay-wharf-3",
    name: "Circular Quay Wharf 3",
    category: "sightseeing",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.860676,151.211517",
  },
  {
    slug: "bondi-to-coogee-walk",
    name: "Bondi to Coogee Walk",
    category: "sightseeing",
    city: "Sydney",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.9183926,151.2584756",
  },
  // ── Blue Mountains ───────────────────────────────────────────────────────
  {
    slug: "valley-of-the-waters",
    name: "Valley of the Waters Lookout",
    category: "sightseeing",
    city: "Blue Mountains",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.720151,150.3628727",
  },
  {
    slug: "grand-canyon-walking-track",
    name: "Grand Canyon Walking Track",
    category: "sightseeing",
    city: "Blue Mountains",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-33.649376,150.3214159",
  },
  // ── Hunter Valley ────────────────────────────────────────────────────────
  {
    slug: "tamburlaine-organic-wines",
    name: "Tamburlaine Organic Wines",
    category: "winery",
    city: "Hunter Valley",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-32.7830981,151.2998123",
  },
  // ── Mudgee ──────────────────────────────────────────────────────────────
  {
    slug: "lowe-family-wine-co",
    name: "Lowe Family Wine Co",
    category: "winery",
    city: "Mudgee",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-32.5372264,149.5852415",
  },
  // ── Orange ──────────────────────────────────────────────────────────────
  {
    slug: "logan-wines",
    name: "Logan Wines",
    category: "winery",
    city: "Orange",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-32.6877708,149.7025299",
  },
  // ── Melbourne ───────────────────────────────────────────────────────────
  {
    slug: "sachi-melbourne",
    name: "Sachi Melbourne",
    category: "food",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.8143727,144.9602655",
  },
  {
    slug: "hectors-deli",
    name: "Hector's Deli",
    category: "food",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.8129127,144.9716793",
  },
  {
    slug: "the-cornish-arms",
    name: "The Cornish Arms Hotel",
    category: "bar",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.7734028,144.9608767",
  },
  {
    slug: "berlin-bar",
    name: "Berlin Bar",
    category: "bar",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.8111309,144.9684355",
  },
  {
    slug: "rooftop-at-qt",
    name: "Rooftop at QT",
    category: "bar",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.8134277,144.9678242",
  },
  {
    slug: "dukes-coffee-roasters",
    name: "Dukes Coffee Roasters",
    category: "coffee",
    city: "Melbourne",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-37.816791,144.966162",
  },
  // ── Brisbane ─────────────────────────────────────────────────────────────
  {
    slug: "hanoi-dna",
    name: "HaNoi DnA",
    category: "food",
    city: "Brisbane",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-27.4582666,153.0334712",
  },
  {
    slug: "madame-wu",
    name: "Madame Wu",
    category: "food",
    city: "Brisbane",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-27.4682005,153.030418",
  },
  {
    slug: "honto",
    name: "hôntô",
    category: "food",
    city: "Brisbane",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-27.4556693,153.0348472",
  },
  {
    slug: "donna-chang",
    name: "Donna Chang",
    category: "food",
    city: "Brisbane",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-27.4717346,153.0245786",
  },
  {
    slug: "the-calile-hotel",
    name: "The Calile Hotel",
    category: "stay",
    city: "Brisbane",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-27.4566167,153.0403719",
  },
  // ── Adelaide ─────────────────────────────────────────────────────────────
  {
    slug: "prohibition-liquor-co",
    name: "Prohibition Liquor Co",
    category: "bar",
    city: "Adelaide",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-34.9341519,138.5993577",
  },
  // ── Cairns ───────────────────────────────────────────────────────────────
  {
    slug: "piccolo-cucina",
    name: "Piccolo Cucina",
    category: "food",
    city: "Cairns",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-16.9239135,145.7786642",
  },
  // ── Hobart ───────────────────────────────────────────────────────────────
  {
    slug: "pancho-villa",
    name: "Pancho Villa",
    category: "food",
    city: "Hobart",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-42.87352,147.315533",
  },
  {
    slug: "westside-laundry",
    name: "Westside Laundry",
    category: "food",
    city: "Hobart",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-42.8863529,147.319673",
  },
  {
    slug: "da-angelo-ristorante",
    name: "Da Angelo Ristorante",
    category: "food",
    city: "Hobart",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-42.8895707,147.3342184",
  },
  // ── Bruny Island ─────────────────────────────────────────────────────────
  {
    slug: "get-shucked",
    name: "Get Shucked",
    category: "food",
    city: "Bruny Island",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-43.1974642,147.3870853",
  },
  // ── Christchurch ─────────────────────────────────────────────────────────
  {
    slug: "hagley-parkrun",
    name: "Hagley parkrun",
    category: "parkrun",
    city: "Christchurch",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-43.5285674,172.6229764",
  },
  {
    slug: "castle-hill-kura-tawhiti",
    name: "Castle Hill / Kura Tawhiti Conservation Area",
    category: "sightseeing",
    city: "Christchurch",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-43.2295617,171.7162282",
  },
  {
    slug: "the-church-pub",
    name: "The Church Pub",
    category: "bar",
    city: "Christchurch",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-43.5311522,172.6393762",
  },
  // ── Singapore ────────────────────────────────────────────────────────────
  {
    slug: "east-coast-park-parkrun",
    name: "East Coast Park parkrun",
    category: "parkrun",
    city: "Singapore",
    note: "",
    mapsUrl: "https://maps.google.com/?q=1.2949434,103.8931212",
  },
  // ── Bali ─────────────────────────────────────────────────────────────────
  {
    slug: "la-favela",
    name: "La Favela",
    category: "bar",
    city: "Bali",
    note: "",
    mapsUrl: "https://maps.google.com/?q=-8.6838942,115.162865",
  },
  // ── Khao Lak ─────────────────────────────────────────────────────────────
  {
    slug: "family-thai-food-and-seafood",
    name: "Family Thai Food & Seafood",
    category: "food",
    city: "Khao Lak",
    note: "",
    mapsUrl: "https://maps.google.com/?q=8.0330281,98.8242132",
  },
  // ── Hội An ───────────────────────────────────────────────────────────────
  {
    slug: "hadi-coffee",
    name: "Hadi Coffee",
    category: "coffee",
    city: "Hội An",
    note: "",
    mapsUrl: "https://maps.google.com/?q=15.8783647,108.3298496",
  },
  {
    slug: "bale-well-restaurant",
    name: "Bale Well Restaurant",
    category: "food",
    city: "Hội An",
    note: "",
    mapsUrl: "https://maps.google.com/?q=15.8788131,108.3300623",
  },
  // ── Hanoi ────────────────────────────────────────────────────────────────
  {
    slug: "bun-cha-huong-lien",
    name: "Bún chả Hương Liên",
    category: "food",
    city: "Hanoi",
    note: "",
    mapsUrl: "https://maps.google.com/?q=21.0181373,105.8538926",
  },
  // ── Nha Trang ────────────────────────────────────────────────────────────
  {
    slug: "skylight-la-kitchen",
    name: "Skylight & Lá Kitchen",
    category: "bar",
    city: "Nha Trang",
    note: "",
    mapsUrl: "https://maps.google.com/?q=12.2433961,109.195842",
  },
  // ── Vang Vieng ───────────────────────────────────────────────────────────
  {
    slug: "viengtara-resort",
    name: "ViengTara VangVieng Resort",
    category: "stay",
    city: "Vang Vieng",
    note: "",
    mapsUrl: "https://maps.google.com/?q=18.9218235,102.444372",
  },
  // ── Luang Prabang ────────────────────────────────────────────────────────
  {
    slug: "avani-luang-prabang",
    name: "Avani+ Luang Prabang Hotel",
    category: "stay",
    city: "Luang Prabang",
    note: "",
    mapsUrl: "https://maps.google.com/?q=19.8885011,102.1337429",
  },
  // ── London ───────────────────────────────────────────────────────────────
  {
    slug: "casse-croute",
    name: "Casse-Croûte",
    category: "food",
    city: "London",
    note: "",
    mapsUrl: "https://maps.google.com/?q=51.50053,-0.0816008",
  },
  {
    slug: "fallow",
    name: "Fallow",
    category: "food",
    city: "London",
    note: "",
    mapsUrl: "https://maps.google.com/?q=51.50941,-0.1327837",
  },
  {
    slug: "osteria-angelina",
    name: "Osteria Angelina",
    category: "food",
    city: "London",
    note: "",
    mapsUrl: "https://maps.google.com/?q=51.5218823,-0.077497",
  },
  // ── Los Angeles ──────────────────────────────────────────────────────────
  {
    slug: "barrique-venice",
    name: "Barrique Venice",
    category: "food",
    city: "Los Angeles",
    note: "",
    mapsUrl: "https://maps.google.com/?q=33.9931638,-118.4746842",
  },
];
